// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA801NpMizdGwcL-S5WZ5FHyt9I8uuwZGc',
    appId: '1:909944346412:web:5f48f205ca9f6550dfbe89',
    messagingSenderId: '909944346412',
    projectId: 'pushtrix',
    authDomain: 'pushtrix.firebaseapp.com',
    databaseURL: 'https://pushtrix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushtrix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTxmGSFftg28OUjL_Z8JTsk6Zx-6Km6s',
    appId: '1:909944346412:android:9cc52e1277dfc8eddfbe89',
    messagingSenderId: '909944346412',
    projectId: 'pushtrix',
    databaseURL: 'https://pushtrix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushtrix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tg0rzGH-x65PFu8dBmnhOuSWTOkvZuY',
    appId: '1:909944346412:ios:582e91dbcf8f2c75dfbe89',
    messagingSenderId: '909944346412',
    projectId: 'pushtrix',
    databaseURL: 'https://pushtrix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushtrix.appspot.com',
    iosClientId: '909944346412-qhr7kujflv4ul8ht77ds6gf1ubr3kpmt.apps.googleusercontent.com',
    iosBundleId: 'com.chengine.pushtrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tg0rzGH-x65PFu8dBmnhOuSWTOkvZuY',
    appId: '1:909944346412:ios:582e91dbcf8f2c75dfbe89',
    messagingSenderId: '909944346412',
    projectId: 'pushtrix',
    databaseURL: 'https://pushtrix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushtrix.appspot.com',
    iosClientId: '909944346412-qhr7kujflv4ul8ht77ds6gf1ubr3kpmt.apps.googleusercontent.com',
    iosBundleId: 'com.chengine.pushtrix',
  );
}
